version: '3.8'

services:

  svc:
    build: .
    ports:
      - "8000:80"
    environment:
      - DB_URL=postgresql://postgres:postgres@db:5432/backend
    depends_on:
      - db

  db:
    image: postgres:13.4
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=backend